# Generated by Django 5.0.3 on 2024-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='wpages',
            field=models.CharField(default='w1', max_length=100),
        ),
    ]
